#!/bin/sh
DIR=$(dirname $0)
CLANG_PATH=$HOME/git/llvm-build/bin
$CLANG_PATH/clang -fsanitize=address -fno-common -fPIC -Wall -O3 -g -D_POSIX_C_SOURCE=200809L $DIR/libc.c -c -o $DIR/libc-asan.o
gcc -fPIC -Wall -mmpx -fcheck-pointer-bounds $DIR/libc.c -c -o $DIR/libc-mpx.o
gcc -Wall -mmpx -fcheck-pointer-bounds -fPIC -O3 -g -D_POSIX_C_SOURCE=200809L $DIR/mpx.c -c -o $DIR/mpx.o
